import { createSlice } from "@reduxjs/toolkit";
import { User } from "@/types/auth.types";
import { PayloadAction } from "@reduxjs/toolkit";

interface AuthSlice {
  accessToken: string | null; // the access token, which is a string or null
  refreshToken: string | null; // the refresh token, which is a string or null
  user: User | null; // the user info, which is an object or null
  isAuthenticated: boolean;
}

const initialState: AuthSlice = {
    accessToken: null, // a JWT token used to call API, which is null by default
    refreshToken: null, // a JWT token used to refresh the access token when the old one expires, which is null by default
    user: null, // the user information, which is null by default
    isAuthenticated: false, // true -> The user logs in
                            // false -> the user logs out
}

const authSlice = createSlice({
    name: 'auth', // the name of the slice, which is used to identify the slice in the Redux store
    initialState, // the initial state of the slice
    reducers: {
        setAccessToken(state, action: PayloadAction<string>) {
            state.accessToken = action.payload;
        }, // set the access token
        clearAuth(state) {
            state.accessToken = null; // set the access token to null
            state.refreshToken = null; // set the refresh token to null
            state.user = null; // set the user info to null
            state.isAuthenticated = false; // set the authentication status to false
        }
    }, // the reducer object that defines all the functions that change AuthState
                  // empty for now
})

export const { setAccessToken, clearAuth } = authSlice.actions;  // export the action creators generated by createSlice, which is used to dispatch actions to change the state of the slice
export default authSlice.reducer; // export the main reducer from the slice