import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { CartState, CartItem } from "@/types/cart.types";
import { Product } from "@/types/product.types";

const initialState: CartState = {
  items: [], // the list of items in the cart, which is an array of objects
  totalItems: 0, // the total number of items in the cart, which is 0 by default
  totalPrice: 0, // the total price of the items in the cart, which is 0 by default
}

const calculateTotals = (items: CartItem[]) => {
  const totalItems = items.reduce(
    (sum, item) => sum + item.quantity, 0
  );
  
  const totalPrice = items.reduce(
    (sum, item) => sum + item.price * item.quantity, 0
  );

  return { totalItems, totalPrice};
} 

const cartSlice = createSlice({
  name: "cart",
  initialState,
  reducers: {
    addToCart: (state, action: PayloadAction<Product>) => {
      // action: PayloadAction<Product> -> the payload of the action is a Product object, which is the product that the user wants to add to the cart
      const existingItem =  state.items.find(
        (item) => item.product.id === action.payload.id
      )  

      if (existingItem) {
        // If the product is found, we will simply increase the count
        existingItem.quantity += 1;
      } else {
        // Otherwise, a new product will be appended to the object
        // -> the product quantity
        // -> the product price

        state.items.push({
          product: action.payload,
          quantity: 1,
          price: action.payload.price,
          id: crypto.randomUUID(), // generate a unique id for the cart item
          cartId: "", 
          productId: action.payload.id,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        })
      }

      // calculate the total using totals
      const totals = calculateTotals(state.items);
      state.totalItems = totals.totalItems;
      state.totalPrice = totals.totalPrice;
    }
  },
})

export const { addToCart } = cartSlice.actions; // export the action creators generated by createSlice
                                     // purpose: dispatch actions to change the state of the cart slice
export default cartSlice.reducer; // export the main reducer from the slice
                                  // purpose: handle the state of the cart slice
