import { createSlice } from "@reduxjs/toolkit";
import { CartState } from "@/types/cart.types";

const initialState: CartState = {
  items: [], // the list of items in the cart, which is an array of objects
  totalItems: 0, // the total number of items in the cart, which is 0 by default
  totalPrice: 0, // the total price of the items in the cart, which is 0 by default
}

const cartSlice = createSlice({
  name: "cart",
  initialState,
  reducers: {},
})

export const {} = cartSlice.actions; // export the action creators generated by createSlice
                                     // purpose: dispatch actions to change the state of the cart slice
export default cartSlice.reducer; // export the main reducer from the slice
                                  // purpose: handle the state of the cart slice
